name: fluxer-tsugu
base: core24
version: '0.0.8'
summary: A free and open source instant messaging and VoIP app
description: |
  A free and open source instant messaging and VoIP platform built for friends, groups, and communities.

grade: stable
confinement: strict

platforms:
  amd64:


parts:
  fluxer-tsugu:
    source: https://api.fluxer.app/dl/desktop/stable/linux/x64/latest/deb
    plugin: dump
    source-type: deb
    stage-packages: [libproxy1v5, libgtk-3-0, libnotify4, libnss3, libxss1, libxtst6, xdg-utils, libatspi2.0-0, libuuid1, libsecret-1-0]

plugs:
  shared-memory:
    private: true

apps:
  fluxer-tsugu:
    command: opt/Fluxer/fluxer --no-sandbox --disable-dev-shm-usage
    extensions: [gnome]
    environment:
      HOME: "$SNAP_USER_DATA"
      TMPDIR: "$XDG_RUNTIME_DIR"
      ELECTRON_DISABLE_SANDBOX: "1"
      LD_LIBRARY_PATH: >
       $SNAP/opt/Fluxer:
       $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:
       $LD_LIBRARY_PATH
    plugs:
      - shared-memory
      - network
      - network-bind
      - home
      - removable-media
      - desktop
      - desktop-legacy
      - audio-playback
      - audio-record
      - x11
      - wayland
      - unity7
      - password-manager-service
      - browser-support
      - opengl
      
